### PR TITLE
Added input argument to allow to specifying the path of the PHP binary to use

### PR DESCRIPTION
**Pull request by Demoboy**
In some environments it might be necessary to test or change the PHP version and it might be located in the server's $PATH. I added a command line argument to the run command to allow specifying the binary to use when running commands.

### CODE REVIEW

**Comment by aggrosoft** [comment]
Why wasn't this merged?

**Comment by stepansib** [comment]
We really need this feature

**Comment by ezprit** [comment]
+1

**Comment by psylosss** [comment]
+1 need it

**Pull request closed without merging**
