### PR TITLE
added function findJobById($id)

### PR DESCRIPTION
**Pull request by tubssp**
added function findJobById($id) to find easy a job by a id.

### CODE REVIEW

**Comment by nclavaud** [comment]
`JobRepository` extends Doctrine's `EntityRepository`, so just use `find()`:
http://symfony.com/doc/current/book/doctrine.html#querying-for-objects

**Comment by schmittjoh** [comment]
Yeah, Doctrine already provides such a method by default.

**Comment by tubssp** [comment]
ok, sorry...

**Comment by schmittjoh** [comment]
No problem, thanks for opening this still :)

**Pull request closed without merging**
